### ISSUE TITLE
Process: create documentation

### ISSUE THREAD

**Issue by Xiphe** [cotype/core#13]
I think we can all agree that this project lacks documentation.

I want to propose that in order to change that we start to add documentation for the feature/bug that we work on in each PR. 

I don't want to create fixed rules on when a PR can be merged or not. But would really like to see each PR to bring a small piece of docs.

What do you think about this? @fgnass @lassediercks @dlehmhus ?

---

This issue can be closed when all participants either agreed on my proposal or it's being declined.

**Comment by dlehmhus** [comment]
In my opinion, documentation would be great. The minimum for every bug should be an entry in the documentation, so we get an overview of how much is missing. In certain circumstances writing the whole documentation for that topic would be too time-consuming.

**Comment by Xiphe** [comment]
Totally agree! I don't want to enforce overhead but rather shift the minds.

**Comment by Xiphe** [comment]
@dlehmhus, @fgnass and me agreed that we should focus on documentation.

We found that its probably also related to https://github.com/cotype/core/issues/17.
Thesis was: due to a lack of documentation and a common understanding of the features & components of the project it is hard to write a meaningful PR description or a clear Issue.

We assume that in order to make the work on this project more transparent and including we need to establish a common language and we want to start with it by focussing on the documentation.

Next: DO IT 🚀
