### ISSUE TITLE
Split index.tsx

### ISSUE THREAD

**Issue by Xiphe** [cotype/core#35]
The [`src/index.ts`](https://github.com/cotype/core/blob/master/src/index.ts) file is getting more and more convoluted. 

I'd propose to move all logic out of it into helpers and only export the API that `@cotype/core` is exposing.

**Comment by Xiphe** [comment]
Any objections/additional ideas @fgnass ?

**Comment by fgnass** [comment]
Sounds good, let's do this.

**Comment by Xiphe** [comment]
Since this does not cause pain atm I will maybe do that when I work on the index next time.
