### ISSUE TITLE
Media e2e tests are highly flaky

### ISSUE THREAD

**Issue by Xiphe** [cotype/core#49]
Please investigate @dlehmhus 

- https://circleci.com/gh/cotype/core/1123
- https://circleci.com/gh/cotype/core/1154
- https://circleci.com/gh/cotype/core/1150
- ...

**Comment by dlehmhus** [comment]
I'm going the deactivate the flaky parts of that test for now until we have found a good solution.

**Comment by Xiphe** [comment]
quickfixed with https://github.com/cotype/core/commit/537dedfccd2d1b08c6f6fdd887d18d2834999873
