### ISSUE TITLE
Consider a z-index manager

### ISSUE THREAD

**Issue by Xiphe** [cotype/core#58]
## Problem

We had ~4 [Patches](https://github.com/cotype/core/releases/tag/v1.12.3) concerning z-index changes since the public release of the lib. [No 5 incoming](https://github.com/cotype/core/commit/2e9ef01b6de8a3cf78c2662cc644d4369b894e7f).

To me this feels like an unstable base I anticipate more similar issues in the future.

## Proposal

Though I've seen similar z-snowball effects in other projects I was not personally involved in solving them. So I don't know what works best but I know there are approaches.

Maybe https://github.com/giuseppeg/react-layers-manager could also be a workaround.

@lassediercks whats your opinion here?

**Comment by fgnass** [comment]
+1 for addressing layer management. I would suggest to add a zindex.ts file like we have it in other projects and only resort to portals if there is no other way to escape the parent's stacking context.

**Comment by fgnass** [comment]
Here's a screenshot of how we deal with z-index-wars in another project:

<img width="573" alt="Screenshot 2019-05-30 at 11 53 45" src="https://user-images.githubusercontent.com/89450/58625281-6b82fb80-82d2-11e9-99d8-585a4b03950a.png">

**Comment by Xiphe** [comment]
apart from being a good idea this does not seem to be relevant enough to activate someone. Closing -> might come up again.
