### ISSUE TITLE
Conflict handling in multi-upload does not work (locally)

### ISSUE THREAD

**Issue by Xiphe** [cotype/core#64]
### Reproduce:

1. Check out latest `master`
2. Start the demo `npm start`
3. open `http://localhost:4000/admin/media`
4. upload two files
5. delete these files
6. upload same files again
7. See a dialoge like this: 
![image](https://user-images.githubusercontent.com/911218/58942308-d1adc980-877d-11e9-9f93-a51c7943fb57.png)
8. Click on the file and see console `Uncaught TypeError: _onSelect is not a function`

**Comment by Xiphe** [comment]
Ux-wise I would expect to have options to either overwrite the file or to ignore it and continue with the others.

**Comment by Xiphe** [comment]
What I picked up from taking to @dlehmhus and @fgnass: 

The main Idea behind this is to prevent multi-uploads from files with the same *content*. 

> When I create a content
> And I upload a file
> And I save the content
> And I create another content
> And I upload the same file again
> And I save the content
> THEN I expect the cms to re-use the file I uploaded earlier
> In order to have better caching

When working in content the file is being exchanged transparently without showing and error to the user. This only appears when working in the Media Tab

**Comment by Xiphe** [comment]
What's the reason we do not also just refer to the existing media entry in multi-file uploads? 

Can't we just get rid of this Dialog completely and handle the de-duplication completely in the background?

**Comment by dlehmhus** [comment]
@Xiphe If I recall it correctly, this dialog was supposed to signal to the user _"hey, we already have a copy of that file, so no there is no need for yet another one. Also, this is why these duplicate files don't show up next to the other new ones"_. I'm not emotionally invested in this dialog, but I think it is not as easy as just getting rid of it. @fgnass any thoughts on this topic?

**Comment by Xiphe** [comment]
https://github.com/cotype/core/issues/85#issuecomment-825549326
