### ISSUE TITLE
"should find all content by search" unit test is flaky

### ISSUE THREAD

**Issue by Xiphe** [cotype/core#75]
Failed runs:

 - https://circleci.com/gh/cotype/core/1679
 - https://circleci.com/gh/cotype/core/1796

**Comment by Xiphe** [comment]
- https://circleci.com/gh/cotype/core/2126?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Xiphe** [comment]
@dlehmhus could you look into this?

**Comment by Xiphe** [comment]
- https://circleci.com/gh/cotype/core/2330?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Xiphe** [comment]
- https://circleci.com/gh/cotype/core/2316

**Comment by Xiphe** [comment]
- https://circleci.com/gh/cotype/core/1991

**Comment by dlehmhus** [comment]
Hopefully this bug got fixed with this test update https://github.com/cotype/core/commit/6a035165759b69b390ac9bc592368238be63a9d9
