### ISSUE TITLE
Proposal: refactor media upload

### ISSUE THREAD

**Issue by Xiphe** [cotype/core#77]
In order to support:

 - pre-signed multi uploads
 - progress-bars for multi uploads in gallery

## Problems

 - In order to do pre-signed uploads, each file needs to be uploaded to a different url
 - When uploading multiple files and the request fails, all files are treated as failed.
 - I can not see progress (preview) on single uploads

## Proposed Solution

 - Split `<UploadZone>` back up into a component for file retrival and another one for uploading
 - Always Handle single uploads (For example in Media view)
   - File objects from dropzone are directly passed into Media Tiles
   - Each tile can create a preview, request a unique pre-signed url, upload and display progress

---

Any Objections/Comments/Ideas? @cotype/maintainers

**Comment by Xiphe** [comment]
ref #65

**Comment by fgnass** [comment]
Sounds good to me.

**Comment by dlehmhus** [comment]
@Xiphe the proposed solution looks good to me, no objections come to my mind!

**Comment by Xiphe** [comment]
Closing since this is included in https://github.com/cotype/core/issues/85
