### ISSUE TITLE
How to check for duplicate files

### ISSUE THREAD

**Issue by Xiphe** [cotype/core#78]
This problem is mainly relevant for the plan to support S3 as file storage.

In order to support the current duplication check flow with pre-signed uploads we would need to do the following:

 - user adds a file for uploading
 - client requests upload url
 - server requests url and passes it back to client
 - client uploads file
 - client notifies server that upload is finished
 - server downloads file
 - server creates file checksum and checks against database
 - server finds duplicate
 - server does not create new media entry but links to existing

The question arising is: Can/Should we check if a file already exists in storage before even uploading it. (For example by hashing it in the browser and checking the server before uploading).

This is partly related to #64 where files with same content but different names are treated as conflict.

Maybe i'm also missing a complete view of the user stories related to this 🤷‍♂

**Comment by fgnass** [comment]
How good would the browser support be for hashing in the browser? Would it work on mobile? As alternative: Could we somehow use the S3 Etag to detect duplicates?

**Comment by fgnass** [comment]
What would be the downside of not using pre-signed URLs at all and piping the files through Node?

**Comment by Xiphe** [comment]
> What would be the downside of not using pre-signed URLs at all and piping the files through Node?

Current implementation of my [S3Storage](https://github.com/cotype/serverless/blob/master/src/S3Storage.ts) does not work in serverless. After debugging it for half a day I stopped investigating and decided that pre-signed uploads are better anyway since they remove the middle-man and potentially support chunked uploads.

> How good would the browser support be for hashing in the browser?

Gegenfrage: Which browsers does cotype support?

> Would it work on mobile?

Does the current file-upload solution work on mobile?

> Could we somehow use the S3 Etag to detect duplicates?

That would still mean: upload files first, then check duplicates. This seems smelly to me.

**Comment by Xiphe** [comment]
For my understanding: 

- Do we care if the same file is being uploaded multiple times?
- If we just replace the file on the server with the same one this should not affect client/cdn caching at all right?
- Main problem is that we do not want multiple entries in the media database for the same file right?

**Comment by Xiphe** [comment]
Closing since this will be included in https://github.com/cotype/core/issues/85
