### ISSUE TITLE
Upload v2

### ISSUE THREAD

**Issue by Xiphe** [cotype/core#85]
In order to support pre-signed uploads in custom storage adapters

Planned flow:

 1. Client wants to upload a file
 2. First set of validation is applied
     1. Check if a global size-limit (set by cotype config) is exceeded (relevant for 2.3.)
     2. (Optional) If uploaded for a content, locally validate against model spec (mime, dimensions). [skip if uploaded into media library]
     3. create local md5, ask server for existing file and try to skip upload if present
         - use [`browser-md5-file`](https://github.com/forsigner/browser-md5-file) (supports IE9+)
         - this step could be skipped for devices that are to slow or do not support FileReader. readAsArrayBuffer. We would just accept duplicates from these devices.
 3. Prepare upload
    - Client notifies server that he wants to upload s.th.
    - Server creates randomized ID & presigned url if required by storage adapter
    - Server creates media DB entry with ID and "pending" flag
    - Server gives uploadUrl and ID to client
 4. Client uploads file to given url
     - If in a content, set media ref using the ID
     - See [Saving before upload is done](#saving-before-upload-done)
 5. The server receiving the file invokes a meta-extraction handler when upload is done
     - (could spawn a cp, invoke a lambda, ...)
     - meta extration handler does its work (receiving image dimensions, mime-type, pdf contents, ...)
     - It should be possible to add custom extrations.
     - extraction handler should have access to db and update the media entry when done
     - If extraction fails, the media entry is moved into an error state containing the error

### content saving

This is only relevant when upload happens in a content

1. Saving is disabled as long as files are uploaded
2. When a content is saved:
    1. Server checks that all media references are not "pending"
        - This could happen when the meta-extraction is not done yet.
        - Server could internally wait for some seconds 
        - If media is still pending, the content is not saved and the client displays a "please retry in a few seconds" message
        - If media is error, that error is returned to client
     2. Server validates media-meta against model spec
     3. Content is saved

### UI/UX-Changes

 - We will introduce a new "Uploads" tab that will only appear when uploads are pending or errored
 - Browser reload/navigation is prevented while a upload is active
 - Each file will be uploaded individually with its own progress bar.
 - If a duplicate is detected, there will be a hint for that file
 - Completed/de-duplicated uploads can be removed in user session by clicking the (x)
 - Errored uploads are displayed even after reload (using error flag in mediaDB)
 - clicking (x) on error uploads removes the error entry from db
 - Uploads pane will periodically check back with server to get updates for pending files

---

- fix #64 by displaying a "de-duplicated" hint in upload pane
- fix #77 by uploading only single files
- fix #78 by using client side de-duplication

**Comment by fgnass** [comment]
2.ii A maybe simpler option would be to perform the validation (size constraints etc.) after the upload is done. So the flow would be the same as if the user picked a file from the gallery. The uploaded file could stay in the library nevertheless. Bonus: The validation would have access to all the extracted meta data.

**Comment by fgnass** [comment]
2.iii It would be fine for me (and also maybe simpler) if the de-duplication was done in the metadata extraction phase (also off-process). When the extraction is done, we have to notify the client anyways and `deduped` could be an info we send along with that response.

**Comment by Xiphe** [comment]
2.ii  - Agree. Will treat client side validation against model spec as optional and make server side validation mandatory.

2.iii - i think the complexity of supporting this is not worth the benefit. 

We need a way to pass the ID of the existing file (in context of the new upload) back to the client. These information is created at a point where there are no pending client requests related to the new upload in the server.

So the server must hold state for the de-duplication for a future client request related to the new uploaded (and de-duplicated) file.

When would we delete that state if ever?

By calculating the hash in client the server does not know that de-duplication exists. It just provides a get id by hash endpoint. Also we're assuming that the amount of browsers not supporting client side hashing should be quite small and we could allow duplicates for them.

I think we can not mix up de-duplication with validation since these two serve quite different purposes. Validation is only applied in context of a content/model. De-duplication is related to a different layer (the media library). A file that is not valid for a content could be valid for another content and therefore should not be deleted. A duplicate should be deleted in any case.

**Comment by Xiphe** [comment]
Short Heads-Up:

Though I hoped to find time to continue my work on this. It currently does not seem realistic. As i'm working 4-5 days for a client and preparing my next winter-trip in the meantime.

I plan to drop in on a friday in the next weeks to sync up with you @cotype/maintainers. 👋

**Comment by Xiphe** [comment]
Sadly I won't have the time to continue contributing to cotype. Therefore closing my issues and branches. As a last step I'm removing stale greenkeeper. Cheers 👋
